# Generated by Django 2.2 on 2021-12-29 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210619_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(default='', max_length=50)),
                ('playcount', models.IntegerField(default=0)),
                ('profilePicture', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
